# Generated by Django 4.1.3 on 2023-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubnoy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Врач'), ('registrar', 'Регистратор'), ('client', 'Клиент')], max_length=10),
        ),
    ]
