# Generated by Django 4.1.3 on 2023-05-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zubnoy_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('price', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_password',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zubnoy_app.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zubnoy_app.clientprofile')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zubnoy_app.schedule')),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zubnoy_app.doctorprofile')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zubnoy_app.service')),
            ],
        ),
    ]
